### ISSUE TITLE
Alarmo Card Unavailable

### ISSUE THREAD

**Issue by jerodjchastain** [nielsfaber/alarmo-card#30]
Alarmo Card is showing unavailable on Lovelace dash after restart.

**Comment by havivi86** [comment]
Yea, also have the same issue. Will love to have this fix...

**Comment by nielsfaber** [comment]
I'm running Alarmo card without problems here on HA 2022.4.
If you want my help, you will need to provide more info.

For example, check your browser logs, see if there is a banner like this one shown:
<img sr=c"https://user-images.githubusercontent.com/16861605/164309618-e3cfc719-75cd-4a30-9c00-8cb8a4ac8a07.png" width="75%" height="75%">
If not: installation issue, this you will have to fix your self.

If yes, check if you have errors in the browser log causing the card to crash.
Also check if the alarm_control_panel entity/entities of alarmo are in HA with correct state (see developer tools -> states).

**Comment by jerodjchastain** [comment]
First let me say the alarmo is great and i just noticed an issue and wasnt even sure how to go about finding the problem. ill will send over the log 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:56:26 PM (10 occurrences)
Last logged: 2:56:33 PM

[139716271399600] Received invalid command: alarmo_updated
[139716271399600] Received invalid command: alarmo/entities
[139716252283520] Received invalid command: mobile_app/push_notification_channel
[139716252215712] Received invalid command: alarmo_updated
[139716162149056] Received invalid command: mobile_app/push_notification_channel


this happens when i restart HA and the alarmo card is up on the lovelace dashboard.
![Alarmo Error](https://user-images.githubusercontent.com/74884062/164313020-6fa2b97f-8cc7-443e-b5f7-73e4c3e8e40d.jpg)

**Comment by jerodjchastain** [comment]
Also its not a huge problem. and the minute i refresh or go to a different lovelace page and come back it comes up fine.

**Comment by havivi86** [comment]
I also want to add to @jerodjchastain, I also love this addon!
In my case, I have tablet mount on the wall, that is always on (using the android app, not the browser). And same with me, every time HA restarts, I get the same error message.

**Comment by nielsfaber** [comment]
@jerodjchastain 
> [139716271399600] Received invalid command: alarmo_updated
[139716271399600] Received invalid command: alarmo/entities
[139716252283520] Received invalid command: mobile_app/push_notification_channel
[139716252215712] Received invalid command: alarmo_updated
[139716162149056] Received invalid command: mobile_app/push_notification_channel

These errors are due to HA still starting up while you are accessing the dashboard.
The websocket_api component of HA takes a bit longer to initialize.
As you can see, this issue is not specific to alarmo, also the mobile_app suffers from this.
You can ignore those messages (I wish I could suppress them, but they are created from HA's side).
The important thing is that the card should refresh once HA has finished loading and the connection is established. this shouldn't

**Comment by jerodjchastain** [comment]
That makes perfect since. I do appreciate you taking the time to explain it to me. Maybe I’ll try and find a way to make ha refresh the Lovelace dash shortly after start up. 

And once again thank you for Alarmo it is great

**Comment by bhirdler** [comment]
No custom:alarmo card option to add. Logs show:

Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 10:09:17 PM (6 occurrences)
Last logged: 10:25:55 PM

http://<ha_ip>/hacsfiles/alarmo-card/alarmo-card.js?hacstag=391372854130:7:1 Uncaught SyntaxError: Unexpected token '<'
http://<ha_ip>/hacsfiles/alarmo-card/alarmo-card.js?hacstag=391372854130:7:0 SyntaxError: expected expression, got '<'
:0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by nielsfaber** [comment]
@bhirdler Looks like an issue with HACS. 
Try manually overwriting the `/www/alarmo-card/alarmo-card.js` file with this file: https://github.com/nielsfaber/alarmo-card/blob/main/dist/alarmo-card.js

**Comment by bhirdler** [comment]
> @bhirdler Looks like an issue with HACS. 
> Try manually overwriting the `/www/alarmo-card/alarmo-card.js` file with this file: https://github.com/nielsfaber/alarmo-card/blob/main/dist/alarmo-card.js

Tried that but still doesn't work.  Went back to previous version and confirmed that card shows up right away

**Comment by bhirdler** [comment]
No custom:alarmo card option to add. Logs show:

Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 10:09:17 PM (6 occurrences)
Last logged: 10:25:55 PM

http://<ha_ip>/hacsfiles/alarmo-card/alarmo-card.js?hacstag=391372854130:7:1 Uncaught SyntaxError: Unexpected token '<'
http://<ha_ip>/hacsfiles/alarmo-card/alarmo-card.js?hacstag=391372854130:7:0 SyntaxError: expected expression, got '<'
:0:0 ResizeObserver loop completed with undelivered notifications.

> @bhirdler Looks like an issue with HACS. Try manually overwriting the `/www/alarmo-card/alarmo-card.js` file with this file: https://github.com/nielsfaber/alarmo-card/blob/main/dist/alarmo-card.js

@nielsfaber - removed it and reinstalled from pc instead of mobile.  Now works fine on PC.  Mobile app still has an issue stating custom app doesn't exist
