### ISSUE TITLE
Alarmo card - Invalid configuration provided for entity

### ISSUE THREAD

**Issue by Tchitan** [nielsfaber/alarmo-card#33]
Hi.
I am running Home Assistant 2022.4.7 on a virtual machine on a Synology NAS, Alarmo V.1.8.7 and Alarmo Card 1.2.3.
I have the Alarmo card instaled in \config\www\community\alarmo-card

<img width="203" alt="image" src="https://user-images.githubusercontent.com/20862871/165199726-704f255e-742a-4157-9284-354772e6182c.png">

but when I add the card to the dashboard it doesn't work. I get an error message "Invalid configuration provided for entity"

<img width="248" alt="image" src="https://user-images.githubusercontent.com/20862871/165199994-a0a8c294-2919-4a38-b966-1bd8923ebf21.png">

Thanks for your help. And thank you for the great work you do!

**Comment by nielsfaber** [comment]
Click edit and choose which alarm entity you want to use.

**Comment by Tchitan** [comment]
I am sorry but I don't understand what you mean. I can only change the name, nothing else.

![image](https://user-images.githubusercontent.com/20862871/165252335-8d012e48-a6bd-4f6e-8890-980bece1b85d.png)

**Comment by flyman1664** [comment]
Hello, same issue on my side
![image](https://user-images.githubusercontent.com/49916159/165345100-1a0844b4-0a65-4b72-9eb7-a74f033ad920.png)

**Comment by nielsfaber** [comment]
I made a release v1.3.0 over one month ago:
![image](https://user-images.githubusercontent.com/16861605/165346142-66f6292a-6a5e-40a9-b7a6-cc9505f15488.png)

However I see I released it wrongly, as a result it is not visible in HACS.
I will correct the release.
This will solve your issues as I can see that a field is missing (due to the card version not being compatible with the HA version).

**Comment by Tchitan** [comment]
I updated to 1.3 but now I can't add it to the dashboard. I see only the alarm panel card, not the alarmo. I refreshed the browser and also restarted HA.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/20862871/165381158-2932ee89-9b2b-4ef3-b3ad-4b390b3bca0d.png">

**Comment by Richdem** [comment]
I have exactly the same issue,

I have installed Alarmo & the V1.3.0 custom card on a test machine and my actually HA machine both running the latest version of HA 2022.4.7. When I try to add a card to my dashboard I only see the standard alarm panel card and not the custom card. I even tried manually installing the custom card but it still did not work

**Comment by nielsfaber** [comment]
You can verify whether the card was installed correctly by consulting your [browser logs](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs):
<img src="https://user-images.githubusercontent.com/16861605/165433641-bdce4846-111c-4d07-baee-49225f209d94.png" width="75%" height="75%">
If alarmo-card is not mentioned here, you need to register it as a [frontend resource](https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/).
Note that the installed version is also shown here, it should show v1.3.0 (otherwise your browser cache needs to be cleared).

If all went fine the card should show up as option when adding a new card to the dashboard (this is assuming you are maintaining your dashboard in UI mode, not YAML mode):
<img src="https://user-images.githubusercontent.com/16861605/165433922-735d8350-c91c-44d2-9912-64eb08c618f3.png" width="50%" height="50%">
The custom cards are all the way in the bottom of the list.

Finally you need to edit the card settings and assign the correct entity to it:
<img src="https://user-images.githubusercontent.com/16861605/165434141-788fe0e5-5f35-4933-beb2-f5209418a79d.png" width="75%" height="75%">

If any of these steps don't work, go back to the browser logs and check for any errors involving the alarmo-card. No errors means no issue which I can solve for you.

So far none of the issues mentioned by any of you indicates that there is a bug in alarmo-card.
This is **not** the right place for asking for help on installation, use the HA forum thread instead (people other than me might be able to help you as well).

**Comment by flyman1664** [comment]
Hi, since the update I'm facing same issue. There is no Alarmo card display.
![image](https://user-images.githubusercontent.com/49916159/165456840-259b2d6a-8b4a-465c-bc67-e8e50fcc45f1.png)

**Comment by Richdem** [comment]
> You can verify whether the card was installed correctly by consulting your [browser logs](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs): <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/16861605/165433641-bdce4846-111c-4d07-baee-49225f209d94.png"> If alarmo-card is not mentioned here, you need to register it as a [frontend resource](https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/). Note that the installed version is also shown here, it should show v1.3.0 (otherwise your browser cache needs to be cleared).
> 
> If all went fine the card should show up as option when adding a new card to the dashboard (this is assuming you are maintaining your dashboard in UI mode, not YAML mode): <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/16861605/165433922-735d8350-c91c-44d2-9912-64eb08c618f3.png"> The custom cards are all the way in the bottom of the list.
> 
> Finally you need to edit the card settings and assign the correct entity to it: <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/16861605/165434141-788fe0e5-5f35-4933-beb2-f5209418a79d.png">
> 
> If any of these steps don't work, go back to the browser logs and check for any errors involving the alarmo-card. No errors means no issue which I can solve for you.
> 
> So far none of the issues mentioned by any of you indicates that there is a bug in alarmo-card. This is **not** the right place for asking for help on installation, use the HA forum thread instead (people other than me might be able to help you as well).

Thank you for replying,

I did post this issue on the HA forum as well. I will have a look at your suggestions later today

**Comment by flyman1664** [comment]
I have installed previous version and the card is available. As soon as I try to update or if I make fresh installation of the new version, the panel card is not available and same error is diplayed into error log.

![image](https://user-images.githubusercontent.com/49916159/165629612-bce715b6-b155-4ccc-9173-2286489bd661.png)

**Comment by Richdem** [comment]
> I have installed previous version and the card is available. As soon as I try to update or if I make fresh installation of the new version, the panel card is not available and same error is diplayed into error log.
> 
> ![image](https://user-images.githubusercontent.com/49916159/165629612-bce715b6-b155-4ccc-9173-2286489bd661.png)
> 
> EDIT: Ok I have done manual installation by uploading the card js to config/www and adding ressources. I think there is an issue with auto installation as the folder alarmo-card is in community folder.

The weird thing is I tried a manual installation twice yesterday on 2 different machines, neither worked. Today I deleted the custom card from my test machine, re installed it and cleared my browser cache again and it worked.

**Comment by erdzan12** [comment]
You have to append manually this to the yaml file of the alarmo card by clicking on `SHOW CODE EDITOR`

```
entity: alarm_control_panel.alarmo
```

**Comment by Tchitan** [comment]
> You have to append manually this to the yaml file of the alarmo card by clicking on `SHOW CODE EDITOR`
> 
> ```
> entity: alarm_control_panel.alarmo
> ```
> 
> The entity name depends on your installation

When I tried to create a new Alarmo card I got this error

![image](https://user-images.githubusercontent.com/20862871/169752667-c96b3dd0-cb5e-42da-9182-3a23cb9f2aeb.png)

but adding the entity line to the card solved it.
Thanks.
For me now everything is working fine.
Great work, thank you.
