### ISSUE TITLE
[Card Settings Panel] Part of the text is hidden with preview

### ISSUE THREAD

**Issue by TaixMiguel** [nielsfaber/alarmo-card#37]
I am sorry to report the bug, as it really is a front error that does not prevent the use of the card.

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version. (v1.4.0)

### Expected behavior
Layer widths should be defined so that when a layer changes (the alarm preview becomes larger) no hidden text is left behind

### Actual behavior
The text explaining the scaling of the buttons looks incomplete due to the alarm panel overlapping a layer above
![Captura de pantalla de 2022-05-07 09-10-35](https://user-images.githubusercontent.com/48259444/167243831-d0b65483-2214-4b7c-97ed-6389c2b43a85.png)
![Captura de pantalla de 2022-05-07 09-11-02](https://user-images.githubusercontent.com/48259444/167243846-07262410-87f2-432a-a655-261f7bbf3c76.png)

### Steps to Reproduce
In the editing of the user interface, when registering an alarmo card you can see the error. In my case, I have a resolution of 1600x900 and I use the browser Firefox

**Comment by nielsfaber** [comment]
I made some changes to the code.
On narrower screen the settings will now be shown below eachother rather than side-by-side.

Here's an example with a display width of 550 pixels (seems similar result to your situation). 

**Before**
<img src="https://user-images.githubusercontent.com/16861605/172064913-8381d001-b453-4f3b-bbac-3b347c8b778e.png" width="50%" height="50%">

**After**
<img src="https://user-images.githubusercontent.com/16861605/172064931-2a6542c0-3061-45c1-a1e3-2956ff2a6784.png" width="50%" height="50%">

**Comment by nielsfaber** [comment]
The changes are now released in v1.4.1.
Please test the result (also your translation), and close the issue if the problem is solved.
Thank you!

**Comment by TaixMiguel** [comment]
![imagen](https://user-images.githubusercontent.com/48259444/172219428-76598f40-f797-40b4-b32f-b72850443be4.png)

The card is seen correctly and on the PC the translations also look correct. I had to reload the browser to see it well (Ctrl + F5), 
I don't know force it in the mobile app, so I will wait for the warning to reload the front.

Thanks for your time
